# Generated by Django 6.0 on 2025-12-08 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Mercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.IntegerField(default=2025)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('origen', models.CharField(default='Manual', max_length=20)),
                ('factor_08', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_09', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_10', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_11', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_12', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_13', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_14', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_15', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_16', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_17', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_18', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_19', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_20', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('factor_37', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.instrumento')),
            ],
        ),
        migrations.AddField(
            model_name='instrumento',
            name='mercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mercado'),
        ),
    ]
