# Generated by Django 6.0 on 2025-12-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='es_isfut',
            field=models.BooleanField(default=False, verbose_name='Acogido a ISFUT/ISIFT'),
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='factor_actualizacion',
            field=models.DecimalField(decimal_places=6, default=1.0, max_digits=10),
        ),
    ]
