# Generated by Django 6.0 on 2025-12-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_calificaciontributaria_factor_21_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='secuencia',
            field=models.IntegerField(default=0),
        ),
    ]
